### ISSUE TITLE
Name is confusing against parcel-bundler/parcel

### ISSUE THREAD

**Issue by windware** [phogolabs/parcello#1]
Can this be renamed to help with search optimization for both projects?

**Comment by KeitIG** [comment]
This is really confusing indeed, Parcel is a 20K stars project and is quite popular in the JS world.

**Comment by damassi** [comment]
Already confusing

**Comment by svett** [comment]
Thank you for the feedback. Indeed it's. I think we should rename it. Do you have any suggestions?

**Comment by svett** [comment]
Just renamed to the repository and the package to `parcello`. I am closing the issue.
